[package]
name = "day02"
version = "0.1.0"
authors = ["Joel Pedraza <joel.pedraza@walmartlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unstable = []

[dependencies]
regex = "1"
lazy_static = "1"